### ISSUE TITLE
Unable to Courier Macros with Multi-Node Content Pickers

### ISSUE THREAD

**Issue by Zhaph** [umbraco/Umbraco.Courier.Issues#10]
Courier does not correctly transfer content items in Macros selected with the Multiple Content Picker - the deployed content is linking to a different content item on the target server.

Digging through the code, I could see that the out of the box configuration doesn't recognise the Multiple Content Picker type and as that was storing the data as CSV in the database, I attempted to add the `MultiNodeContentPicker`. 

Reproduction
------------

### Bug summary

Updating the courier.config to include the `Umbraco.MultiNodeTreePicker` (the type the Multiple Content Picker identifies as) results in an error when collecting resources

```xml
<macroPropertyTypeResolvers>
  <contentPickers>
    <!-- Macro Property Types, that store Content IDs, to link to media or content -->
    <add key="contentPicker">Umbraco.ContentPickerAlias</add>
    <add key="multiplemediaPicker">Umbraco.MultipleMediaPicker</add>
    <add key="mediaPicker">Umbraco.MediaPicker</add>
    <add key="MNTP-CSV">Umbraco.MultiNodeTreePicker</add>
  </contentPickers>
 </macroPropertyTypeResolvers>
```

The Umbraco pane displays the following message:

**Server was unable to process the request ---> Could not proceed, no content type found with alias product** 

Error in logs:

```
2019-06-17 10:28:04,427 [P11816/D2/T53] ERROR Umbraco.Courier.Core.TaskManager - [Thread 53] Error PackagingTask with id: 30ac3d43-903f-4f63-9507-a4f3e2b40130
System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> Could not proceed, no content type found with alias product
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.EndInvoke(IAsyncResult asyncResult)
   at Umbraco.Courier.RepositoryProviders.WebServiceProvider.RepositoryWebservice.EndGetHashes(IAsyncResult asyncResult)
   at Umbraco.Courier.RepositoryProviders.CourierWebserviceRepositoryProvider.GetHashes(ItemIdentifier[] itemIds)
   at Umbraco.Courier.Core.Packaging.RevisionPackaging.GetTargetHashes(IPackagingTarget2 target, IEnumerable`1 ids)
   at Umbraco.Courier.Core.Packaging.RevisionPackaging.PackageBatch()
   at Umbraco.Courier.Core.Packaging.RevisionPackaging.Package()
   at Umbraco.Courier.Core.Tasks.PackagingTask.Run()
   at Umbraco.Courier.Core.BackgroundTaskRunner`1.ConsumeTaskInternal(T task)
2019-06-17 10:28:04,484 [P11816/D2/T53] ERROR Umbraco.Courier.Core.BackgroundTaskRunner - [Thread 53] An error occurred consuming task
System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> Could not proceed, no content type found with alias product
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.EndInvoke(IAsyncResult asyncResult)
   at Umbraco.Courier.RepositoryProviders.WebServiceProvider.RepositoryWebservice.EndGetHashes(IAsyncResult asyncResult)
   at Umbraco.Courier.RepositoryProviders.CourierWebserviceRepositoryProvider.GetHashes(ItemIdentifier[] itemIds)
   at Umbraco.Courier.Core.Packaging.RevisionPackaging.GetTargetHashes(IPackagingTarget2 target, IEnumerable`1 ids)
   at Umbraco.Courier.Core.Packaging.RevisionPackaging.PackageBatch()
   at Umbraco.Courier.Core.Packaging.RevisionPackaging.Package()
   at Umbraco.Courier.Core.Tasks.PackagingTask.Run()
   at Umbraco.Courier.Core.BackgroundTaskRunner`1.ConsumeTaskInternal(T task)
```

Stepping through the code used by the target server (SOAP message sent to `/umbraco/plugins/courier/webservices/repository.asmx?fromExternalClient=true`) I can see that the packager has listed these dependencies as "media" items, rather than the expected "content" items. The call to `GetHashes` looked like (extra rows removed for brevity):

```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <soap:Header>
        <CourierSoapAuthentication soap:mustUnderstand="1" xmlns="http://umbraco.com/courier">
            [...]
        </CourierSoapAuthentication>
    </soap:Header>
    <soap:Body>
        <GetHashes xmlns="http://courier.umbraco.org/">
        <sessionKey>70d16f67-3b89-4fdf-b432-631ff440dbd7</sessionKey>
            <itemIds>
                <ItemIdentifier>
                    <Id>0f02af2a-351c-4e12-95dc-4adc61f9797c</Id>
                    <ProviderId>d8e6ad87-e73a-11df-9492-0800200c9a66</ProviderId>
                </ItemIdentifier>
                <ItemIdentifier>
                    <Id>4dca554d-cb60-4ff7-87e0-337aa355aea1</Id>
                    <ProviderId>d8e6ad87-e73a-11df-9492-0800200c9a66</ProviderId>
                </ItemIdentifier>
            </itemIds>
        </GetHashes>
    </soap:Body>
</soap:Envelope>
```

The provider ID for those items appears to map to "media" and then the content item isn't found correctly.

Switching the configuration to use `Umbraco.MultiNodeContentPicker2` results in the original behaviour (i.e. content deployed by integer id).

### Specifics

Umbraco Version: 7.14.0
Courier Version: 3.1.6 for v7

### Steps to reproduce

Create a macro with two parameters - a Text Box and a Multiple Content Picker.

Add the macro to a page, enter some text in the text field and select two or more items in the content picker.

Courier the page.

Note that on the target server the Macro links to different content (if at all) if the Integer Ids of the selected content do not align between servers.

Update Courier to include `Umbraco.MultiNodeContentPicker`

Attempt to courier the page.

### Expected result

Content is correctly deployed to the target server, and the correct content items are linked in the Multiple Content Picker

### Actual result

At best no content is selected in the Multiple Content Picker, at worst the wrong content is selected.

**Comment by Zhaph** [comment]
I have the same issue if I try with the hotfix files from #8 - I noticed in there that you have added the `MultiNodeContentPicker2` to the ContentPickers and MediaPickers elements in courier.config as well - however this didn't seem to help in my initial testing.

**Comment by jmcaveney** [comment]
Has this been reviewed at all? Running into an issue with the MNTP and Macros on a courier enabled site.

**Comment by nul800sebastiaan** [comment]
Hi there @Zhaph, we're writing you today to let you know that Umbraco Courier has entered the security phase earlier this month, as described in the following blog post: [Announcement: Support, LTS and EOL for Umbraco CMS, Cloud and packages](https://umbraco.com/blog/announcement-support-lts-and-eol-for-umbraco-cms-cloud-and-packages/).

This means that we're no longer working on Umbraco Courier issues and in March 2022 we will also stop fixing security issue and Courier is considered EOL (End Of Life) and we no longer recommend using it.

As such, I will be closing this issue.
