### ISSUE TITLE
Cannot deploy revision

### ISSUE THREAD

**Issue by ismailmayat** [umbraco/Umbraco.Courier.Issues#17]
Using Umbraco 7.15.4 and courier 3.7.  I create a revision on my source. I then transfer revision to target. When I try to deploy the transferred revision i get the following error.
Unhandled exception occurred.

Status: 500

Message: error

ExceptionType: System.Collections.Generic.KeyNotFoundException

Message: The given key was not present in the dictionary.

StackTrace:

   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.ObjectModel.KeyedCollection`2.get_Item(TKey key)
   at Umbraco.Courier.Core.GraphNodeCollection.MarkAsSkipped(ItemIdentifier id)
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.Extract()
   at Umbraco.Courier.Core.Tasks.ExtractionTask.Run()
   at Umbraco.Courier.Core.BackgroundTaskRunner`1.ConsumeTaskInternal(T task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Courier.Core.TaskManager.GetSuccessfulProcessedTasks()
   at Umbraco.Courier.UI.Pages.ViewTaskManager.GetProcessed()

**Comment by nul800sebastiaan** [comment]
Hi Ismail, this is not something I feel like I can help with without being able to reproduce this in a similar environment as yours. Please make sure to contact the support department so they can help get this debugged.
