### ISSUE TITLE
It is impossible to courier after change groups in public access

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco.Courier.Issues#19]
### Details
Umbraco version: 7.15.5
Courier version: 3.1.8
### What is happening:|
Everytime when I will change Groups in public access I am getting 500 error on courier with following error log:

```2020-08-19 12:09:41,164 [41] ERROR Umbraco.Courier.Core.TaskManager - [Thread 41] Error ExtractionTask with id: c1f99cd7-11d3-4c7e-844f-aeebc8a5478f
System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> Error extracting item, ID:GUID_GUID, Name: GROUPNAME, Type: Umbraco.Courier.ItemProviders.Document ---> could not execute batch command.[SQL: SQL not available] ---> Cannot insert the value NULL into column 'accessId', table 'umbraco.dbo.umbracoAccessRule'; column does not allow nulls. UPDATE fails.
The statement has been terminated.
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.EndInvoke(IAsyncResult asyncResult)
   at Umbraco.Courier.RepositoryProviders.WebServiceProvider.RepositoryWebservice.EndExtractItems(IAsyncResult asyncResult)
   at Umbraco.Courier.RepositoryProviders.CourierWebserviceRepositoryProvider.ExtractItems(Item[] items, Boolean overWrite)
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.ExtractItems(List`1 nodes)
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.ExtractReadyRevisionBatch()
   at Umbraco.Courier.Core.Extraction.RevisionExtraction.Extract()
   at Umbraco.Courier.Core.Tasks.ExtractionTask.Run()
   at Umbraco.Courier.Core.BackgroundTaskRunner`1.ConsumeTaskInternal(T task)
```

### What should happen:
After change of PA i should be able to courier site.
### Steps to reproduce:

1. Create site
2. Add public access
3. Courier
4. Change groups in PA
5. Courier

---
_This item has been added to our backlog [AB#9981](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/9981)_

**Comment by nul800sebastiaan** [comment]
Hi there @bielu, we're writing you today to let you know that Umbraco Courier has entered the security phase earlier this month, as described in the following blog post: [Announcement: Support, LTS and EOL for Umbraco CMS, Cloud and packages](https://umbraco.com/blog/announcement-support-lts-and-eol-for-umbraco-cms-cloud-and-packages/).

This means that we're no longer working on Umbraco Courier issues and in March 2022 we will also stop fixing security issue and Courier is considered EOL (End Of Life) and we no longer recommend using it.

As such, I will be closing this issue.
